### PR TITLE
Add the semi supervised folder and it's scripts

### PR DESCRIPTION
**Pull request by GuillermoFidalgo**

### CODE REVIEW

**Comment by deguio** [comment]
hi @GuillermoFidalgo 
few comments.

- files `.pyc` shouldn't be pushed to github
- I would try not to duplicate the utilities files. you can just leave those under the main notebooks folder

could you update and push to the same branch? the pull request will update automatically.

**Comment by deguio** [comment]
@GuillermoFidalgo 
I made some comments to your original PR. would it be possible to implement them?

**Comment by GuillermoFidalgo** [comment]
How do you recommend I remove the .pyc files?
git rm 
or just rm?

Also I am not sure how to import the utils file if it is not in the same path as the script.
I believe it complains if the utils file is not present.

**Comment by vkhristenko** [comment]
- first git rm those
- second, update hte .gitignore with `*.pyc`
- commit push

**Comment by GuillermoFidalgo** [comment]
Thanks!

**Pull request merged**
